[context.production]
  environment = { NODE_VERSION = "15.3.0" }
[build]
  command = "npm run build"
  publish = "build/"
  functions = "functions/"
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
